global:
  scrape_interval:     1s 
  evaluation_interval: 1s 

  external_labels:
      monitor: 'log-check'

rule_files:

scrape_configs:
  - job_name: "db-prometheus"
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'db-postgres-exporter'
    scrape_interval: 1s
    static_configs:
      - targets: ['db-postgres-exporter:9187']
