
INSERT INTO public."WANT_COMP_NAME_TB"( "COMP_NAME_NM")
	VALUES ('wanted');
	
INSERT INTO public."WANT_TAG_TB"("TAG_NM")
	VALUES ('태그1');

INSERT INTO public."WANT_MAPPED_COMP_NAME_TB"("COMP_NAME_ID", "MAPPED_COMP_NAME_NM")
	VALUES (1,'wanted');

INSERT INTO public."WANT_MAPPED_TAG_TB"("TAG_ID", "MAPPED_TAG_NM")
	VALUES (1,'태그1');
	
INSERT INTO public."WANT_COMP_N_TAG_TB"("COMP_TAG_ID", "COMP_NAME_ID")
	VALUES (1,1);
	

